// <auto-generated />
using System;
using JobTrackin.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace JobTrackin.Api.Persistence.Migrations
{
    [DbContext(typeof(JobTrackinDbContext))]
    [Migration("20260905131933_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobTrackin.Api.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<string>("ApplicationSource")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("APPLICATION_SOURCE_ID");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("APPLIED_AT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("COMPANY");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("CURRENCY_CODE");

                    b.Property<string>("CurrentStatusId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CURRENT_STATUS_ID");

                    b.Property<string>("DiscoverySource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DISCOVERY_SOURCE_ID");

                    b.Property<string>("EmailReference")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("EMAIL_REFERENCE");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("JOB_TYPE");

                    b.Property<string>("JobUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("JOB_URL");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("LOCATION");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB")
                        .HasColumnName("NOTES");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("ROLE_TITLE");

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("SALARY_MAX");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("SALARY_MIN");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("TENANT_ID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("WorkMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("WORK_MODE");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStatusId");

                    b.HasIndex("TenantId", "AppliedAt");

                    b.ToTable("APPLICATION", (string)null);
                });

            modelBuilder.Entity("JobTrackin.Api.Domain.Entities.ApplicationStatus", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DISPLAY_NAME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<int>("SortOrder")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SORT_ORDER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("APPLICATION_STATUS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "SAVED",
                            Code = "SAVED",
                            DisplayName = "Saved",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "APPLIED",
                            Code = "APPLIED",
                            DisplayName = "Applied",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "UNDER_REVIEW",
                            Code = "UNDER_REVIEW",
                            DisplayName = "Under Review",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "INTERVIEW",
                            Code = "INTERVIEW",
                            DisplayName = "Interview Scheduled",
                            IsActive = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = "ASSESSMENT",
                            Code = "ASSESSMENT",
                            DisplayName = "Assessment",
                            IsActive = true,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = "OFFER",
                            Code = "OFFER",
                            DisplayName = "Offer Received",
                            IsActive = true,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = "REJECTED",
                            Code = "REJECTED",
                            DisplayName = "Rejected",
                            IsActive = true,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = "WITHDRAWN",
                            Code = "WITHDRAWN",
                            DisplayName = "Withdrawn",
                            IsActive = true,
                            SortOrder = 8
                        },
                        new
                        {
                            Id = "ACCEPTED",
                            Code = "ACCEPTED",
                            DisplayName = "Offer Accepted",
                            IsActive = true,
                            SortOrder = 9
                        },
                        new
                        {
                            Id = "UNKNOWN",
                            Code = "UNKNOWN",
                            DisplayName = "Unknown",
                            IsActive = true,
                            SortOrder = 10
                        });
                });

            modelBuilder.Entity("JobTrackin.Api.Domain.Entities.Application", b =>
                {
                    b.HasOne("JobTrackin.Api.Domain.Entities.ApplicationStatus", "CurrentStatus")
                        .WithMany()
                        .HasForeignKey("CurrentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
